{
 "title": "DEV: Grafanalib-Components",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "Environment", "query": "label_values(env)" },
   { "name": "Cluster", "query": "label_values(cluster)" },
   {
    "name": "Deployment",
    "query": "\"summary-reader\",\"summary-writer\",\"api\",\"epoch-reader-1\",\"epoch-reader-2\",\"epoch-writer\",\"front\",\"gql\",\"homeshard\",\"ingestion-pipeline\",\"queue\",\"worker\""
   },
   {
    "name": "Node",
    "query": "label_values(kube_node_info, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "Deployment memory usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod=~\"$Environment-$Deployment.*$\", node=~\"^$Node$\",env=~\"^$Environment.*$\",cluster=~\"^$Cluster.*$\"}) / sum (kube_node_status_allocatable{resource=\"memory\",node=~\"^$Node$\",env=~\"^$Environment.*$\",cluster=~\"^$Cluster.*$\"}) * 100"
    }
   ]
  },
  {
   "title": "Deployment CPU usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod=~\"$Environment-$Deployment.*$\",node=~\"^$Node$\",env=~\"^$Environment.*$\",cluster=~\"^$Cluster.*$\"}[1m])) / sum (kube_node_status_capacity{resource=\"cpu\",node=~\"^$Node$\",env=~\"^$Environment.*$\",cluster=~\"^$Cluster.*$\"}) * 100"
    }
   ]
  },
  {
   "title": "Deployment CPU Usage/Requests/Limits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{env=~\"$Environment\",cluster=~\"^$Cluster\",pod=~\"$Environment-$Deployment.*\", container=~\"tomcat|summary\"}[5m]))",
     "legendFormat": "Average CPU Usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{resource=\"cpu\",env=~\"$Environment\",cluster=~\"^$Cluster\",exported_pod=~\"$Environment-$Deployment.*\", exported_container=~\"tomcat|summary\"})",
     "legendFormat": "CPU Requests"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{resource=\"cpu\",env=~\"$Environment\",cluster=~\"^$Cluster\",exported_pod=~\"$Environment-$Deployment.*\", exported_container=~\"tomcat|summary\"})",
     "legendFormat": "CPU Limits"
    },
    {
     "expr": "avg(rate(container_cpu_cfs_throttled_seconds_total{env=~\"$Environment\",cluster=~\"^$Cluster\",pod=~\"$Environment-$Deployment.*\", container=~\"tomcat|summary\"}[5m]))",
     "legendFormat": "Average CPU throttling rate"
    }
   ]
  }
 ]
}